# Generated by Django 3.1.5 on 2021-03-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20210305_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='book',
            new_name='content',
        ),
    ]
