# Generated by Django 3.1.5 on 2021-03-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20210305_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isbn', models.IntegerField()),
                ('pageCount', models.IntegerField()),
                ('publishedDate', models.JSONField()),
                ('thumbnailUrl', models.URLField()),
                ('shortDescription', models.CharField(max_length=1000)),
                ('longDescription', models.CharField(max_length=3000)),
                ('status', models.CharField(max_length=100)),
                ('authors', models.JSONField()),
                ('categories', models.JSONField()),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
