# Generated by Django 3.1.5 on 2021-03-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='Wishlist',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
