# Generated by Django 3.1.5 on 2021-03-15 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0005_auto_20210309_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='content',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='books',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='wishlist', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
