# Generated by Django 3.1.5 on 2021-03-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20210314_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.JSONField(null=True),
        ),
    ]
