# Generated by Django 3.1.5 on 2021-03-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_auto_20210314_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
