# Generated by Django 3.1.5 on 2021-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='Book',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='User',
            field=models.JSONField(null=True),
        ),
    ]
