# Generated by Django 3.1.5 on 2021-03-19 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_auto_20210319_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
