# Generated by Django 3.1.5 on 2021-03-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0012_wishlist_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='title',
            new_name='name',
        ),
    ]
