# Generated by Django 3.1.6 on 2021-02-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Book',
        ),
    ]
