# Generated by Django 3.1.5 on 2021-02-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
