# Generated by Django 3.1.5 on 2021-03-09 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore_api', '0003_auto_20210305_2012'),
        ('bookstore_api', '0003_auto_20210302_1459'),
    ]

    operations = [
    ]
