# Generated by Django 3.1.5 on 2021-03-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookstore_api', '0004_merge_20210309_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='wishlist',
            field=models.JSONField(null=True),
        ),
    ]
