# Generated by Django 3.1.5 on 2021-03-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0005_userprofiles_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='wishlist',
            field=models.JSONField(default='empty', null=True),
        ),
    ]
