# Generated by Django 3.1.5 on 2021-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0005_auto_20210308_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='catetgory',
            field=models.CharField(default='java', max_length=100),
            preserve_default=False,
        ),
    ]
