# Generated by Django 3.1.5 on 2021-03-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0006_auto_20210309_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='wishlist',
            field=models.JSONField(null=True),
        ),
    ]
