# Generated by Django 3.1.5 on 2021-03-26 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0006_book_catetgory'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='book',
            name='authorName',
            field=models.CharField(default='auhtor', max_length=100),
            preserve_default=False,
        ),
       
        migrations.AddField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
    