# Generated by Django 3.1.5 on 2021-03-15 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0007_auto_20210309_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
