# Generated by Django 3.1.5 on 2021-03-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0006_book_catetgory'),
        ('bookstore_api', '0009_remove_userprofiles_date_created'),
    ]

    operations = [
    ]
