# Generated by Django 3.1.5 on 2021-03-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0010_merge_20210326_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='wishlist',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist', models.JSONField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('userProfiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_api.userprofiles')),
            ],
        ),
    ]
