# Generated by Django 3.1.5 on 2021-03-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0013_userprofiles_wishlistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='wishlistName',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
