# Generated by Django 3.1.5 on 2021-04-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0014_auto_20210328_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorName',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='authorbio',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='fullurl',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
