# Generated by Django 3.1.5 on 2021-04-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0015_auto_20210401_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='wishlist2',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='wishlist2Name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='authorName',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
