# Generated by Django 3.1.5 on 2021-04-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0016_auto_20210401_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='wishlist2',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='wishlist2Name',
        ),
    ]
