# Generated by Django 3.1.5 on 2021-04-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0017_auto_20210401_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='wishlist2',
            field=models.JSONField(null=True),
        ),
    ]
