# Generated by Django 3.1.5 on 2021-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0021_userprofiles_wishlist3name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authorName',
            field=models.CharField(max_length=100),
        ),
    ]
